// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package HeartStatus;

public interface StatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.StatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double Beats = 1;</code>
   */
  double getBeats();
}
