// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package HeartStatus;

public interface StatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.StatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string classif = 1;</code>
   */
  java.lang.String getClassif();
  /**
   * <code>string classif = 1;</code>
   */
  com.google.protobuf.ByteString
      getClassifBytes();
}
