// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface runAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.runAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 distance = 1;</code>
   */
  int getDistance();

  /**
   * <code>int32 AvgVelocity = 2;</code>
   */
  int getAvgVelocity();
}
