// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface runDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.runData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string runMode = 1;</code>
   */
  java.lang.String getRunMode();
  /**
   * <code>string runMode = 1;</code>
   */
  com.google.protobuf.ByteString
      getRunModeBytes();

  /**
   * <code>int32 steps = 2;</code>
   */
  int getSteps();

  /**
   * <code>double time = 3;</code>
   */
  double getTime();
}
