// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public final class Service2Impl {
  private Service2Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_runData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_runData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_runAnalysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_runAnalysis_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_sportData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_sportData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_sportAnalysis_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_sportAnalysis_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service2.proto\022\010wearGRPC\"7\n\007runData\022\017\n" +
      "\007runMode\030\001 \001(\t\022\r\n\005steps\030\002 \001(\005\022\014\n\004time\030\003 " +
      "\001(\001\"4\n\013runAnalysis\022\020\n\010distance\030\001 \001(\005\022\023\n\013" +
      "AvgVelocity\030\002 \001(\005\"C\n\tsportData\022\023\n\013typeAc" +
      "tvity\030\001 \001(\t\022\017\n\007theGoal\030\002 \001(\001\022\020\n\010duration" +
      "\030\003 \001(\001\"8\n\rsportAnalysis\022\026\n\016caloriesBurne" +
      "d\030\001 \001(\005\022\017\n\007theGoal\030\002 \001(\0012\204\001\n\010Service2\0227\n" +
      "\007running\022\021.wearGRPC.runData\032\025.wearGRPC.r" +
      "unAnalysis\"\0000\001\022?\n\tsportMode\022\023.wearGRPC.s" +
      "portData\032\027.wearGRPC.sportAnalysis\"\000(\0010\001B" +
      "\034\n\nwatchSportB\014Service2ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearGRPC_runData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearGRPC_runData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_runData_descriptor,
        new java.lang.String[] { "RunMode", "Steps", "Time", });
    internal_static_wearGRPC_runAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearGRPC_runAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_runAnalysis_descriptor,
        new java.lang.String[] { "Distance", "AvgVelocity", });
    internal_static_wearGRPC_sportData_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wearGRPC_sportData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_sportData_descriptor,
        new java.lang.String[] { "TypeActvity", "TheGoal", "Duration", });
    internal_static_wearGRPC_sportAnalysis_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wearGRPC_sportAnalysis_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_sportAnalysis_descriptor,
        new java.lang.String[] { "CaloriesBurned", "TheGoal", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
