// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface sportAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.sportAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 caloriesBurned = 1;</code>
   */
  int getCaloriesBurned();

  /**
   * <code>string theGoal = 2;</code>
   */
  java.lang.String getTheGoal();
  /**
   * <code>string theGoal = 2;</code>
   */
  com.google.protobuf.ByteString
      getTheGoalBytes();

  /**
   * <code>string quote = 3;</code>
   */
  java.lang.String getQuote();
  /**
   * <code>string quote = 3;</code>
   */
  com.google.protobuf.ByteString
      getQuoteBytes();
}
