// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface sportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.sportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string typeActvity = 1;</code>
   */
  java.lang.String getTypeActvity();
  /**
   * <code>string typeActvity = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeActvityBytes();

  /**
   * <code>double theGoal = 2;</code>
   */
  double getTheGoal();

  /**
   * <code>double duration = 3;</code>
   */
  double getDuration();
}
