// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

/**
 * <pre>
 *Calories burned - RPC Bidirectional
 * </pre>
 *
 * Protobuf type {@code wearGRPC.sportData}
 */
public  final class sportData extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wearGRPC.sportData)
    sportDataOrBuilder {
private static final long serialVersionUID = 0L;
  // Use sportData.newBuilder() to construct.
  private sportData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private sportData() {
    typeActvity_ = "";
    theGoal_ = 0D;
    duration_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private sportData(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            typeActvity_ = s;
            break;
          }
          case 17: {

            theGoal_ = input.readDouble();
            break;
          }
          case 25: {

            duration_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return watchSport.Service2Impl.internal_static_wearGRPC_sportData_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return watchSport.Service2Impl.internal_static_wearGRPC_sportData_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            watchSport.sportData.class, watchSport.sportData.Builder.class);
  }

  public static final int TYPEACTVITY_FIELD_NUMBER = 1;
  private volatile java.lang.Object typeActvity_;
  /**
   * <code>string typeActvity = 1;</code>
   */
  public java.lang.String getTypeActvity() {
    java.lang.Object ref = typeActvity_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeActvity_ = s;
      return s;
    }
  }
  /**
   * <code>string typeActvity = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTypeActvityBytes() {
    java.lang.Object ref = typeActvity_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeActvity_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int THEGOAL_FIELD_NUMBER = 2;
  private double theGoal_;
  /**
   * <code>double theGoal = 2;</code>
   */
  public double getTheGoal() {
    return theGoal_;
  }

  public static final int DURATION_FIELD_NUMBER = 3;
  private double duration_;
  /**
   * <code>double duration = 3;</code>
   */
  public double getDuration() {
    return duration_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTypeActvityBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, typeActvity_);
    }
    if (theGoal_ != 0D) {
      output.writeDouble(2, theGoal_);
    }
    if (duration_ != 0D) {
      output.writeDouble(3, duration_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTypeActvityBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, typeActvity_);
    }
    if (theGoal_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, theGoal_);
    }
    if (duration_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, duration_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof watchSport.sportData)) {
      return super.equals(obj);
    }
    watchSport.sportData other = (watchSport.sportData) obj;

    boolean result = true;
    result = result && getTypeActvity()
        .equals(other.getTypeActvity());
    result = result && (
        java.lang.Double.doubleToLongBits(getTheGoal())
        == java.lang.Double.doubleToLongBits(
            other.getTheGoal()));
    result = result && (
        java.lang.Double.doubleToLongBits(getDuration())
        == java.lang.Double.doubleToLongBits(
            other.getDuration()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TYPEACTVITY_FIELD_NUMBER;
    hash = (53 * hash) + getTypeActvity().hashCode();
    hash = (37 * hash) + THEGOAL_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTheGoal()));
    hash = (37 * hash) + DURATION_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getDuration()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static watchSport.sportData parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchSport.sportData parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchSport.sportData parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchSport.sportData parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchSport.sportData parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchSport.sportData parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchSport.sportData parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static watchSport.sportData parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static watchSport.sportData parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static watchSport.sportData parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static watchSport.sportData parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static watchSport.sportData parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(watchSport.sportData prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Calories burned - RPC Bidirectional
   * </pre>
   *
   * Protobuf type {@code wearGRPC.sportData}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wearGRPC.sportData)
      watchSport.sportDataOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchSport.Service2Impl.internal_static_wearGRPC_sportData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchSport.Service2Impl.internal_static_wearGRPC_sportData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              watchSport.sportData.class, watchSport.sportData.Builder.class);
    }

    // Construct using watchSport.sportData.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      typeActvity_ = "";

      theGoal_ = 0D;

      duration_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return watchSport.Service2Impl.internal_static_wearGRPC_sportData_descriptor;
    }

    @java.lang.Override
    public watchSport.sportData getDefaultInstanceForType() {
      return watchSport.sportData.getDefaultInstance();
    }

    @java.lang.Override
    public watchSport.sportData build() {
      watchSport.sportData result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public watchSport.sportData buildPartial() {
      watchSport.sportData result = new watchSport.sportData(this);
      result.typeActvity_ = typeActvity_;
      result.theGoal_ = theGoal_;
      result.duration_ = duration_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof watchSport.sportData) {
        return mergeFrom((watchSport.sportData)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(watchSport.sportData other) {
      if (other == watchSport.sportData.getDefaultInstance()) return this;
      if (!other.getTypeActvity().isEmpty()) {
        typeActvity_ = other.typeActvity_;
        onChanged();
      }
      if (other.getTheGoal() != 0D) {
        setTheGoal(other.getTheGoal());
      }
      if (other.getDuration() != 0D) {
        setDuration(other.getDuration());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      watchSport.sportData parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (watchSport.sportData) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object typeActvity_ = "";
    /**
     * <code>string typeActvity = 1;</code>
     */
    public java.lang.String getTypeActvity() {
      java.lang.Object ref = typeActvity_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeActvity_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string typeActvity = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTypeActvityBytes() {
      java.lang.Object ref = typeActvity_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeActvity_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string typeActvity = 1;</code>
     */
    public Builder setTypeActvity(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeActvity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string typeActvity = 1;</code>
     */
    public Builder clearTypeActvity() {
      
      typeActvity_ = getDefaultInstance().getTypeActvity();
      onChanged();
      return this;
    }
    /**
     * <code>string typeActvity = 1;</code>
     */
    public Builder setTypeActvityBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeActvity_ = value;
      onChanged();
      return this;
    }

    private double theGoal_ ;
    /**
     * <code>double theGoal = 2;</code>
     */
    public double getTheGoal() {
      return theGoal_;
    }
    /**
     * <code>double theGoal = 2;</code>
     */
    public Builder setTheGoal(double value) {
      
      theGoal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double theGoal = 2;</code>
     */
    public Builder clearTheGoal() {
      
      theGoal_ = 0D;
      onChanged();
      return this;
    }

    private double duration_ ;
    /**
     * <code>double duration = 3;</code>
     */
    public double getDuration() {
      return duration_;
    }
    /**
     * <code>double duration = 3;</code>
     */
    public Builder setDuration(double value) {
      
      duration_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double duration = 3;</code>
     */
    public Builder clearDuration() {
      
      duration_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wearGRPC.sportData)
  }

  // @@protoc_insertion_point(class_scope:wearGRPC.sportData)
  private static final watchSport.sportData DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new watchSport.sportData();
  }

  public static watchSport.sportData getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<sportData>
      PARSER = new com.google.protobuf.AbstractParser<sportData>() {
    @java.lang.Override
    public sportData parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new sportData(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<sportData> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<sportData> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public watchSport.sportData getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

