// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface sportDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.sportData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string typeActvity = 1;</code>
   */
  java.lang.String getTypeActvity();
  /**
   * <code>string typeActvity = 1;</code>
   */
  com.google.protobuf.ByteString
      getTypeActvityBytes();

  /**
   * <code>int32 AvgVelocity = 2;</code>
   */
  int getAvgVelocity();

  /**
   * <code>double durationTime = 3;</code>
   */
  double getDurationTime();

  /**
   * <code>int32 basalMetab = 4;</code>
   */
  int getBasalMetab();
}
