// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service2.proto

package watchSport;

public interface sportAnalysisOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.sportAnalysis)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 caloriesBurned = 1;</code>
   */
  int getCaloriesBurned();

  /**
   * <code>double theGoal = 2;</code>
   */
  double getTheGoal();
}
