// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package smartGlasses;

public interface activationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.activation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bluetoothYes = 1;</code>
   */
  java.lang.String getBluetoothYes();
  /**
   * <code>string bluetoothYes = 1;</code>
   */
  com.google.protobuf.ByteString
      getBluetoothYesBytes();
}
