// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package smartGlasses;

public interface choseVideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.choseVideo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playVideo = 1;</code>
   */
  java.lang.String getPlayVideo();
  /**
   * <code>string playVideo = 1;</code>
   */
  com.google.protobuf.ByteString
      getPlayVideoBytes();
}
