// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package smartGlasses;

public interface confirmActivationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.confirmActivation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string conected = 1;</code>
   */
  java.lang.String getConected();
  /**
   * <code>string conected = 1;</code>
   */
  com.google.protobuf.ByteString
      getConectedBytes();
}
