// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package smartGlasses;

public interface playingVideoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.playingVideo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string playing = 1;</code>
   */
  java.lang.String getPlaying();
  /**
   * <code>string playing = 1;</code>
   */
  com.google.protobuf.ByteString
      getPlayingBytes();
}
