// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package GetHeartBeats;

public interface BeatsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.BeatsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double BeatH = 1;</code>
   */
  double getBeatH();
}
