// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package GetHeartBeats;

/**
 * Protobuf type {@code wearGRPC.BeatsServerStreamRequest}
 */
public  final class BeatsServerStreamRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wearGRPC.BeatsServerStreamRequest)
    BeatsServerStreamRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use BeatsServerStreamRequest.newBuilder() to construct.
  private BeatsServerStreamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private BeatsServerStreamRequest() {
    measure_ = 0;
    intervalB_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private BeatsServerStreamRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            measure_ = input.readInt32();
            break;
          }
          case 16: {

            intervalB_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return GetHeartBeats.Service3Impl.internal_static_wearGRPC_BeatsServerStreamRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return GetHeartBeats.Service3Impl.internal_static_wearGRPC_BeatsServerStreamRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            GetHeartBeats.BeatsServerStreamRequest.class, GetHeartBeats.BeatsServerStreamRequest.Builder.class);
  }

  public static final int MEASURE_FIELD_NUMBER = 1;
  private int measure_;
  /**
   * <code>int32 measure = 1;</code>
   */
  public int getMeasure() {
    return measure_;
  }

  public static final int INTERVALB_FIELD_NUMBER = 2;
  private int intervalB_;
  /**
   * <pre>
   * time in seconds
   * </pre>
   *
   * <code>int32 intervalB = 2;</code>
   */
  public int getIntervalB() {
    return intervalB_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (measure_ != 0) {
      output.writeInt32(1, measure_);
    }
    if (intervalB_ != 0) {
      output.writeInt32(2, intervalB_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (measure_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, measure_);
    }
    if (intervalB_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, intervalB_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof GetHeartBeats.BeatsServerStreamRequest)) {
      return super.equals(obj);
    }
    GetHeartBeats.BeatsServerStreamRequest other = (GetHeartBeats.BeatsServerStreamRequest) obj;

    boolean result = true;
    result = result && (getMeasure()
        == other.getMeasure());
    result = result && (getIntervalB()
        == other.getIntervalB());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MEASURE_FIELD_NUMBER;
    hash = (53 * hash) + getMeasure();
    hash = (37 * hash) + INTERVALB_FIELD_NUMBER;
    hash = (53 * hash) + getIntervalB();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static GetHeartBeats.BeatsServerStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(GetHeartBeats.BeatsServerStreamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wearGRPC.BeatsServerStreamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wearGRPC.BeatsServerStreamRequest)
      GetHeartBeats.BeatsServerStreamRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return GetHeartBeats.Service3Impl.internal_static_wearGRPC_BeatsServerStreamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return GetHeartBeats.Service3Impl.internal_static_wearGRPC_BeatsServerStreamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              GetHeartBeats.BeatsServerStreamRequest.class, GetHeartBeats.BeatsServerStreamRequest.Builder.class);
    }

    // Construct using GetHeartBeats.BeatsServerStreamRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      measure_ = 0;

      intervalB_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return GetHeartBeats.Service3Impl.internal_static_wearGRPC_BeatsServerStreamRequest_descriptor;
    }

    @java.lang.Override
    public GetHeartBeats.BeatsServerStreamRequest getDefaultInstanceForType() {
      return GetHeartBeats.BeatsServerStreamRequest.getDefaultInstance();
    }

    @java.lang.Override
    public GetHeartBeats.BeatsServerStreamRequest build() {
      GetHeartBeats.BeatsServerStreamRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public GetHeartBeats.BeatsServerStreamRequest buildPartial() {
      GetHeartBeats.BeatsServerStreamRequest result = new GetHeartBeats.BeatsServerStreamRequest(this);
      result.measure_ = measure_;
      result.intervalB_ = intervalB_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof GetHeartBeats.BeatsServerStreamRequest) {
        return mergeFrom((GetHeartBeats.BeatsServerStreamRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(GetHeartBeats.BeatsServerStreamRequest other) {
      if (other == GetHeartBeats.BeatsServerStreamRequest.getDefaultInstance()) return this;
      if (other.getMeasure() != 0) {
        setMeasure(other.getMeasure());
      }
      if (other.getIntervalB() != 0) {
        setIntervalB(other.getIntervalB());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      GetHeartBeats.BeatsServerStreamRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (GetHeartBeats.BeatsServerStreamRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int measure_ ;
    /**
     * <code>int32 measure = 1;</code>
     */
    public int getMeasure() {
      return measure_;
    }
    /**
     * <code>int32 measure = 1;</code>
     */
    public Builder setMeasure(int value) {
      
      measure_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 measure = 1;</code>
     */
    public Builder clearMeasure() {
      
      measure_ = 0;
      onChanged();
      return this;
    }

    private int intervalB_ ;
    /**
     * <pre>
     * time in seconds
     * </pre>
     *
     * <code>int32 intervalB = 2;</code>
     */
    public int getIntervalB() {
      return intervalB_;
    }
    /**
     * <pre>
     * time in seconds
     * </pre>
     *
     * <code>int32 intervalB = 2;</code>
     */
    public Builder setIntervalB(int value) {
      
      intervalB_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * time in seconds
     * </pre>
     *
     * <code>int32 intervalB = 2;</code>
     */
    public Builder clearIntervalB() {
      
      intervalB_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wearGRPC.BeatsServerStreamRequest)
  }

  // @@protoc_insertion_point(class_scope:wearGRPC.BeatsServerStreamRequest)
  private static final GetHeartBeats.BeatsServerStreamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new GetHeartBeats.BeatsServerStreamRequest();
  }

  public static GetHeartBeats.BeatsServerStreamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<BeatsServerStreamRequest>
      PARSER = new com.google.protobuf.AbstractParser<BeatsServerStreamRequest>() {
    @java.lang.Override
    public BeatsServerStreamRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new BeatsServerStreamRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<BeatsServerStreamRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<BeatsServerStreamRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public GetHeartBeats.BeatsServerStreamRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

