// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package GetHeartBeats;

public interface BeatsServerStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.BeatsServerStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 measure = 1;</code>
   */
  int getMeasure();

  /**
   * <pre>
   * time in seconds
   * </pre>
   *
   * <code>int32 intervalB = 2;</code>
   */
  int getIntervalB();
}
