// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service3.proto

package GetHeartBeats;

public final class Service3Impl {
  private Service3Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_BeatsServerStreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_BeatsServerStreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_BeatsResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_BeatsResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service3.proto\022\010wearGRPC\">\n\030BeatsServe" +
      "rStreamRequest\022\017\n\007measure\030\001 \001(\005\022\021\n\tinter" +
      "valB\030\002 \001(\005\"\036\n\rBeatsResponse\022\r\n\005BeatH\030\001 \001" +
      "(\0012_\n\rGetHeartBeats\022N\n\rGetHeartBeats\022\".w" +
      "earGRPC.BeatsServerStreamRequest\032\027.wearG" +
      "RPC.BeatsResponse0\001B\037\n\rGetHeartBeatsB\014Se" +
      "rvice3ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearGRPC_BeatsServerStreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearGRPC_BeatsServerStreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_BeatsServerStreamRequest_descriptor,
        new java.lang.String[] { "Measure", "IntervalB", });
    internal_static_wearGRPC_BeatsResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearGRPC_BeatsResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_BeatsResponse_descriptor,
        new java.lang.String[] { "BeatH", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
