// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface avgHeartRateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.avgHeartRate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 avgHeartRate = 1;</code>
   */
  int getAvgHeartRate();
}
