// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface heartBeatOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.heartBeat)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 heartBeat = 1;</code>
   */
  int getHeartBeat();
}
