// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface MovimentRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.MovimentRequest)
    com.google.protobuf.MessageOrBuilder {
}
