// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface SendAlertOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.SendAlert)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string noMoviment = 1;</code>
   */
  java.lang.String getNoMoviment();
  /**
   * <code>string noMoviment = 1;</code>
   */
  com.google.protobuf.ByteString
      getNoMovimentBytes();
}
