// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_MovimentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_MovimentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_StatusSedentary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_StatusSedentary_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_heartBeat_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_heartBeat_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_avgHeartRate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_avgHeartRate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010wearGRPC\"\021\n\017MovimentRe" +
      "quest\"*\n\017StatusSedentary\022\027\n\017messagSedent" +
      "ary\030\001 \001(\t\"\036\n\theartBeat\022\021\n\theartBeat\030\001 \001(" +
      "\005\"$\n\014avgHeartRate\022\024\n\014avgHeartRate\030\001 \001(\0052" +
      "\225\001\n\010Service1\022K\n\021sedentaryReminder\022\031.wear" +
      "GRPC.MovimentRequest\032\031.wearGRPC.StatusSe" +
      "dentary\"\000\022<\n\theartRate\022\023.wearGRPC.heartB" +
      "eat\032\026.wearGRPC.avgHeartRate\"\000(\001B\035\n\013watch" +
      "HealthB\014Service1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearGRPC_MovimentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearGRPC_MovimentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_MovimentRequest_descriptor,
        new java.lang.String[] { });
    internal_static_wearGRPC_StatusSedentary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearGRPC_StatusSedentary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_StatusSedentary_descriptor,
        new java.lang.String[] { "MessagSedentary", });
    internal_static_wearGRPC_heartBeat_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_wearGRPC_heartBeat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_heartBeat_descriptor,
        new java.lang.String[] { "HeartBeat", });
    internal_static_wearGRPC_avgHeartRate_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_wearGRPC_avgHeartRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_avgHeartRate_descriptor,
        new java.lang.String[] { "AvgHeartRate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
