// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public final class Service1Impl {
  private Service1Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_MovimentRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_MovimentRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_StatusSedentary_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_StatusSedentary_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service1.proto\022\010wearGRPC\"\021\n\017MovimentRe" +
      "quest\"*\n\017StatusSedentary\022\027\n\017messagSedent" +
      "ary\030\001 \001(\t2W\n\010Service1\022K\n\021sedentaryRemind" +
      "er\022\031.wearGRPC.MovimentRequest\032\031.wearGRPC" +
      ".StatusSedentary\"\000B\035\n\013watchHealthB\014Servi" +
      "ce1ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearGRPC_MovimentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearGRPC_MovimentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_MovimentRequest_descriptor,
        new java.lang.String[] { });
    internal_static_wearGRPC_StatusSedentary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearGRPC_StatusSedentary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_StatusSedentary_descriptor,
        new java.lang.String[] { "MessagSedentary", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
