// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface StatusSedentaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.StatusSedentary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string SedentaryAlert = 1;</code>
   */
  java.lang.String getSedentaryAlert();
  /**
   * <code>string SedentaryAlert = 1;</code>
   */
  com.google.protobuf.ByteString
      getSedentaryAlertBytes();
}
