// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface StatusSedentaryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ds.service1.StatusSedentary)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string messagSedentary = 1;</code>
   */
  java.lang.String getMessagSedentary();
  /**
   * <code>string messagSedentary = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessagSedentaryBytes();
}
