// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface stepResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.stepResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string result = 1;</code>
   */
  java.lang.String getResult();
  /**
   * <code>string result = 1;</code>
   */
  com.google.protobuf.ByteString
      getResultBytes();

  /**
   * <code>double avgSpeed = 2;</code>
   */
  double getAvgSpeed();

  /**
   * <code>int32 currentC = 3;</code>
   */
  int getCurrentC();
}
