// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface stepRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.stepRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  boolean hasStepStatus();
  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  watchHealth.stepStatus getStepStatus();
  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  watchHealth.stepStatusOrBuilder getStepStatusOrBuilder();
}
