// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

/**
 * Protobuf type {@code wearGRPC.stepRequest}
 */
public  final class stepRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:wearGRPC.stepRequest)
    stepRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use stepRequest.newBuilder() to construct.
  private stepRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private stepRequest() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private stepRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            watchHealth.stepStatus.Builder subBuilder = null;
            if (stepStatus_ != null) {
              subBuilder = stepStatus_.toBuilder();
            }
            stepStatus_ = input.readMessage(watchHealth.stepStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(stepStatus_);
              stepStatus_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return watchHealth.Service1Impl.internal_static_wearGRPC_stepRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return watchHealth.Service1Impl.internal_static_wearGRPC_stepRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            watchHealth.stepRequest.class, watchHealth.stepRequest.Builder.class);
  }

  public static final int STEPSTATUS_FIELD_NUMBER = 1;
  private watchHealth.stepStatus stepStatus_;
  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  public boolean hasStepStatus() {
    return stepStatus_ != null;
  }
  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  public watchHealth.stepStatus getStepStatus() {
    return stepStatus_ == null ? watchHealth.stepStatus.getDefaultInstance() : stepStatus_;
  }
  /**
   * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
   */
  public watchHealth.stepStatusOrBuilder getStepStatusOrBuilder() {
    return getStepStatus();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (stepStatus_ != null) {
      output.writeMessage(1, getStepStatus());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (stepStatus_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStepStatus());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof watchHealth.stepRequest)) {
      return super.equals(obj);
    }
    watchHealth.stepRequest other = (watchHealth.stepRequest) obj;

    boolean result = true;
    result = result && (hasStepStatus() == other.hasStepStatus());
    if (hasStepStatus()) {
      result = result && getStepStatus()
          .equals(other.getStepStatus());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStepStatus()) {
      hash = (37 * hash) + STEPSTATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStepStatus().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static watchHealth.stepRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchHealth.stepRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchHealth.stepRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchHealth.stepRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchHealth.stepRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static watchHealth.stepRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static watchHealth.stepRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static watchHealth.stepRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static watchHealth.stepRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static watchHealth.stepRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static watchHealth.stepRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static watchHealth.stepRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(watchHealth.stepRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code wearGRPC.stepRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:wearGRPC.stepRequest)
      watchHealth.stepRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return watchHealth.Service1Impl.internal_static_wearGRPC_stepRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return watchHealth.Service1Impl.internal_static_wearGRPC_stepRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              watchHealth.stepRequest.class, watchHealth.stepRequest.Builder.class);
    }

    // Construct using watchHealth.stepRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (stepStatusBuilder_ == null) {
        stepStatus_ = null;
      } else {
        stepStatus_ = null;
        stepStatusBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return watchHealth.Service1Impl.internal_static_wearGRPC_stepRequest_descriptor;
    }

    @java.lang.Override
    public watchHealth.stepRequest getDefaultInstanceForType() {
      return watchHealth.stepRequest.getDefaultInstance();
    }

    @java.lang.Override
    public watchHealth.stepRequest build() {
      watchHealth.stepRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public watchHealth.stepRequest buildPartial() {
      watchHealth.stepRequest result = new watchHealth.stepRequest(this);
      if (stepStatusBuilder_ == null) {
        result.stepStatus_ = stepStatus_;
      } else {
        result.stepStatus_ = stepStatusBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof watchHealth.stepRequest) {
        return mergeFrom((watchHealth.stepRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(watchHealth.stepRequest other) {
      if (other == watchHealth.stepRequest.getDefaultInstance()) return this;
      if (other.hasStepStatus()) {
        mergeStepStatus(other.getStepStatus());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      watchHealth.stepRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (watchHealth.stepRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private watchHealth.stepStatus stepStatus_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        watchHealth.stepStatus, watchHealth.stepStatus.Builder, watchHealth.stepStatusOrBuilder> stepStatusBuilder_;
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public boolean hasStepStatus() {
      return stepStatusBuilder_ != null || stepStatus_ != null;
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public watchHealth.stepStatus getStepStatus() {
      if (stepStatusBuilder_ == null) {
        return stepStatus_ == null ? watchHealth.stepStatus.getDefaultInstance() : stepStatus_;
      } else {
        return stepStatusBuilder_.getMessage();
      }
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public Builder setStepStatus(watchHealth.stepStatus value) {
      if (stepStatusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        stepStatus_ = value;
        onChanged();
      } else {
        stepStatusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public Builder setStepStatus(
        watchHealth.stepStatus.Builder builderForValue) {
      if (stepStatusBuilder_ == null) {
        stepStatus_ = builderForValue.build();
        onChanged();
      } else {
        stepStatusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public Builder mergeStepStatus(watchHealth.stepStatus value) {
      if (stepStatusBuilder_ == null) {
        if (stepStatus_ != null) {
          stepStatus_ =
            watchHealth.stepStatus.newBuilder(stepStatus_).mergeFrom(value).buildPartial();
        } else {
          stepStatus_ = value;
        }
        onChanged();
      } else {
        stepStatusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public Builder clearStepStatus() {
      if (stepStatusBuilder_ == null) {
        stepStatus_ = null;
        onChanged();
      } else {
        stepStatus_ = null;
        stepStatusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public watchHealth.stepStatus.Builder getStepStatusBuilder() {
      
      onChanged();
      return getStepStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    public watchHealth.stepStatusOrBuilder getStepStatusOrBuilder() {
      if (stepStatusBuilder_ != null) {
        return stepStatusBuilder_.getMessageOrBuilder();
      } else {
        return stepStatus_ == null ?
            watchHealth.stepStatus.getDefaultInstance() : stepStatus_;
      }
    }
    /**
     * <code>.wearGRPC.stepStatus stepStatus = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        watchHealth.stepStatus, watchHealth.stepStatus.Builder, watchHealth.stepStatusOrBuilder> 
        getStepStatusFieldBuilder() {
      if (stepStatusBuilder_ == null) {
        stepStatusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            watchHealth.stepStatus, watchHealth.stepStatus.Builder, watchHealth.stepStatusOrBuilder>(
                getStepStatus(),
                getParentForChildren(),
                isClean());
        stepStatus_ = null;
      }
      return stepStatusBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:wearGRPC.stepRequest)
  }

  // @@protoc_insertion_point(class_scope:wearGRPC.stepRequest)
  private static final watchHealth.stepRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new watchHealth.stepRequest();
  }

  public static watchHealth.stepRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<stepRequest>
      PARSER = new com.google.protobuf.AbstractParser<stepRequest>() {
    @java.lang.Override
    public stepRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new stepRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<stepRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<stepRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public watchHealth.stepRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

