// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service1.proto

package watchHealth;

public interface stepStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.stepStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool actived = 1;</code>
   */
  boolean getActived();

  /**
   * <code>int32 count = 2;</code>
   */
  int getCount();
}
