// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package AvgHeartBeat;

public interface GetHeartBeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.GetHeartBeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numberQual = 1;</code>
   */
  int getNumberQual();
}
