// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package AvgHeartBeat;

public interface GetHeartBeatResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:wearGRPC.GetHeartBeatResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double avgHeart = 1;</code>
   */
  double getAvgHeart();
}
