// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: service4.proto

package AvgHeartBeat;

public final class Service4Impl {
  private Service4Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_GetHeartBeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_GetHeartBeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_wearGRPC_GetHeartBeatResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_wearGRPC_GetHeartBeatResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016service4.proto\022\010wearGRPC\")\n\023GetHeartBe" +
      "atRequest\022\022\n\nnumberQual\030\001 \001(\005\"(\n\024GetHear" +
      "tBeatResponse\022\020\n\010avgHeart\030\001 \001(\0012_\n\014AvgHe" +
      "artBeat\022O\n\014AvgHeartBeat\022\035.wearGRPC.GetHe" +
      "artBeatRequest\032\036.wearGRPC.GetHeartBeatRe" +
      "sponse(\001B\036\n\014AvgHeartBeatB\014Service4ImplP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_wearGRPC_GetHeartBeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_wearGRPC_GetHeartBeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_GetHeartBeatRequest_descriptor,
        new java.lang.String[] { "NumberQual", });
    internal_static_wearGRPC_GetHeartBeatResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_wearGRPC_GetHeartBeatResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_wearGRPC_GetHeartBeatResponse_descriptor,
        new java.lang.String[] { "AvgHeart", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
